version: '3.9'

services:
  # Section service database section
  # mysql container service
  db_mysql:
    # image: mysql:5.7.22
    image: mysql:8.0.23
    container_name: db_mysql
    restart: always
    ports:
      - 33066:3306
    environment:
      MYSQL_DATABASE: fullstack_go_react
      MYSQL_USER: adminx
      MYSQL_PASWORD: adminx
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  # phpmyadmin container service
  # this service is work depends on mysql container service (db_mysql)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - 8081:80
    links:
      - db_mysql
    environment:
      PMA_HOST: db_mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - db_mysql
volumes:
  dbdata:
